WITH all_collisions AS (
    SELECT * FROM collisions
)

SELECT BOROUGH, COUNT(*) AS cnt,"CONTRIBUTING FACTOR VEHICLE 1" FROM all_collisions
WHERE BOROUGH IS NOT NULL AND "CONTRIBUTING FACTOR VEHICLE 1" IS NOT NULL
GROUP BY BOROUGH, "CONTRIBUTING FACTOR VEHICLE 1"
HAVING cnt > 1000
ORDER BY BOROUGH ASC